# Generated by Django 5.2.6 on 2025-09-09 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_patientmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothChartModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_chart', to='account.patientmodel', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Tooth Chart',
                'verbose_name_plural': 'Tooth Charts',
            },
        ),
        migrations.CreateModel(
            name='ToothModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='Tooth Number')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('removed', 'Removed')], default='healthy', max_length=30, verbose_name='Status')),
                ('position', models.CharField(choices=[('UR', 'Upper Right'), ('UL', 'Upper Left'), ('LR', 'Lower Right'), ('LL', 'Lower Left')], help_text='Tooth quadrant for UI layout', max_length=2, verbose_name='Quadrant')),
                ('color_code', models.CharField(blank=True, help_text='Used for UI coloring', max_length=12, verbose_name='Color Code')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='teeth.toothchartmodel', verbose_name='Tooth Chart')),
            ],
            options={
                'verbose_name': 'Tooth',
                'verbose_name_plural': 'Teeth',
                'unique_together': {('chart', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OcclusionLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('adjacent', 'Adjacent'), ('antagonist', 'Antagonist')], default='adjacent', max_length=20, verbose_name='Relation Type')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occlusion_links', to='teeth.toothchartmodel', verbose_name='Tooth Chart')),
                ('source_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='teeth.toothmodel', verbose_name='Source Tooth')),
                ('target_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='teeth.toothmodel', verbose_name='Target Tooth')),
            ],
            options={
                'verbose_name': 'Occlusion Link',
                'verbose_name_plural': 'Occlusion Links',
                'unique_together': {('source_tooth', 'target_tooth', 'relation')},
            },
        ),
    ]
