# Generated by Django 5.2.6 on 2025-09-09 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_patientmodel_options'),
        ('catalog', '0001_initial'),
        ('teeth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='account.patientmodel', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Treatment Case',
                'verbose_name_plural': 'Treatment Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseToothModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_teeth', to='treatment.casemodel', verbose_name='Case')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_usages', to='teeth.toothmodel', verbose_name='Tooth')),
            ],
            options={
                'verbose_name': 'Case Tooth',
                'verbose_name_plural': 'Case Teeth',
                'unique_together': {('case', 'tooth')},
            },
        ),
        migrations.CreateModel(
            name='CaseItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_items', to='catalog.materialmodel', verbose_name='Material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_items', to='catalog.servicemodel', verbose_name='Service')),
                ('case_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatment.casetoothmodel', verbose_name='Case Tooth')),
            ],
            options={
                'verbose_name': 'Case Item',
                'verbose_name_plural': 'Case Items',
            },
        ),
        migrations.CreateModel(
            name='CaseItemOptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('case_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='treatment.caseitemmodel', verbose_name='Case Item')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_usages', to='catalog.optionmodel', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Case Item Option',
                'verbose_name_plural': 'Case Item Options',
                'unique_together': {('case_item', 'option')},
            },
        ),
        migrations.CreateModel(
            name='MirrorCopyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy_type', models.CharField(choices=[('adjacent', 'Adjacent Tooth'), ('antagonist', 'Antagonist Tooth')], default='adjacent', max_length=20, verbose_name='Copy Type')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_copies', to='treatment.casemodel', verbose_name='Case')),
                ('source_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_from', to='treatment.casetoothmodel', verbose_name='Source Tooth')),
                ('target_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_to', to='treatment.casetoothmodel', verbose_name='Target Tooth')),
            ],
            options={
                'verbose_name': 'Mirror Copy',
                'verbose_name_plural': 'Mirror Copies',
                'unique_together': {('source_tooth', 'target_tooth', 'copy_type')},
            },
        ),
    ]
