# Generated by Django 5.2.6 on 2025-09-10 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='cases/%Y/%m/%d/', verbose_name='ّFile')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('stl', 'STL'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20, verbose_name='ّFile Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_private', models.BooleanField(default=True, help_text='If True, the download link requires authentication', verbose_name='Is Private')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='treatment.casemodel', verbose_name='Case')),
                ('linked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='treatment.caseitemmodel', verbose_name='Linked Item')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Case Attachment',
                'verbose_name_plural': 'Case Attachments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['case', 'linked_item'], name='treatment_c_case_id_d3bbe0_idx')],
            },
        ),
    ]
