# Generated by Django 5.2.6 on 2025-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_caseattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseitemoptionmodel',
            name='value',
            field=models.JSONField(default=dict, help_text='The selected value is typed (e.g. bool / int / float / list / str)', verbose_name='Value'),
        ),
    ]
