# Generated by Django 5.2.6 on 2025-09-09 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Price List Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='SurchargeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Surcharge Name')),
                ('type', models.CharField(choices=[('urgency', 'Urgency'), ('color', 'Special Color'), ('complexity', 'Complexity'), ('custom', 'Custom Surcharge')], default='custom', max_length=20, verbose_name='Surcharge Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Surcharge',
                'verbose_name_plural': 'Surcharges',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('responded', 'Responded'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='treatment.casemodel', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
            },
        ),
        migrations.CreateModel(
            name='QuoteItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Suggested Price')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.materialmodel', verbose_name='Material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='catalog.servicemodel', verbose_name='Service')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.quoterequestmodel', verbose_name='Quote Request')),
            ],
            options={
                'verbose_name': 'Quote Item',
                'verbose_name_plural': 'Quote Items',
            },
        ),
        migrations.CreateModel(
            name='ServicePriceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('service', 'Service Only'), ('material', 'Material Only'), ('combo', 'Service + Material')], default='combo', max_length=20, verbose_name='Scope')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.materialmodel', verbose_name='Material')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='pricing.pricelistmodel', verbose_name='Price List')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.servicemodel', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
                'unique_together': {('price_list', 'service', 'material')},
            },
        ),
        migrations.CreateModel(
            name='CaseSurchargeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='treatment.casemodel', verbose_name='Case')),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='pricing.surchargemodel', verbose_name='Surcharge')),
            ],
            options={
                'verbose_name': 'Case Surcharge',
                'verbose_name_plural': 'Case Surcharges',
                'unique_together': {('case', 'surcharge')},
            },
        ),
    ]
