# Generated by Django 5.2.6 on 2025-09-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmodel',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
