# Generated by Django 5.2.6 on 2025-09-10 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.optionmodel', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Option Choices',
                'verbose_name_plural': 'Option Choices',
                'ordering': ('order',),
                'unique_together': {('option', 'value')},
            },
        ),
        migrations.CreateModel(
            name='OptionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_values', models.JSONField(help_text='list or single value', verbose_name='Expected Values')),
                ('effect', models.CharField(choices=[('visibility', 'Visibility'), ('required', 'Required'), ('enable', 'Enable')], default='visibility', max_length=20)),
                ('match_mode', models.CharField(choices=[('any', 'any'), ('all', 'all')], default='any', max_length=10)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='catalog.optionmodel', verbose_name='Depends On')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='catalog.optionmodel', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Option Dependency',
                'verbose_name_plural': 'Option Dependents',
                'indexes': [models.Index(fields=['option', 'depends_on'], name='catalog_opt_option__e96460_idx')],
            },
        ),
    ]
