# Generated by Django 5.2.6 on 2025-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_optionchoice_optiondependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiondependency',
            name='effect',
            field=models.CharField(choices=[('visibility', 'Visibility'), ('required', 'Required'), ('enable', 'Enable')], default='visibility', max_length=20, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='optiondependency',
            name='match_mode',
            field=models.CharField(choices=[('any', 'any'), ('all', 'all')], default='any', max_length=10, verbose_name='Match Mode'),
        ),
    ]
